export enum LocalStorageKeyEnum {
  name = 'name',
  userName = 'userName',
  lastName = 'lastName',
  rol = 'rolUser',
  token = 'token',
  type = 'type',
}

export enum RolesEnum {
  SUPERVISOR = 'SUPERVISOR',
  USER = 'USER',
  P_CAMPO = 'P_CAMPO',
  AGENTE = 'AGENTE',
}

export var arrayMunicipios:any=[
  {viewValue: 'POPAYAN'},
  {viewValue: 'ALMAGUER'},
  {viewValue: 'ARGELIA'},
  {viewValue: 'BALBOA'},
  {viewValue: 'BOLIVAR'},
  {viewValue: 'BUENOS AIRES'},
  {viewValue: 'CAJIBIO'},
  {viewValue: 'CALDONO'},
  {viewValue: 'CALOTO'},
  {viewValue: 'CORINTO'},
  {viewValue: 'EL TAMBO'},
  {viewValue: 'FLORENCIA'},
  {viewValue: 'GUACHENE'},
  {viewValue: 'GUAPI'},
  {viewValue: 'INZA'},
  {viewValue: 'JAMBALO'},
  {viewValue: 'LA SIERRA'},
  {viewValue: 'LA VEGA'},
  {viewValue: 'LOPEZ'},
  {viewValue: 'MERCADERES'},
  {viewValue: 'MIRANDA'},
  {viewValue: 'MORALES'},
  {viewValue: 'PADILLA'},
  {viewValue: 'PAEZ'},
  {viewValue: 'PIAMONTE'},
  {viewValue: 'PIENDAMO'},
  {viewValue: 'PUERTO TEJADA'},
  {viewValue: 'PATIA'},
  {viewValue: 'PURACE'},
  {viewValue: 'ROSAS'},
  {viewValue: 'SAN SEBASTIAN'},
  {viewValue: 'SANTANDER DE QUILICHAO'},
  {viewValue: 'SANTA ROSA'},
  {viewValue: 'SILVIA'},
  {viewValue: 'SOTARA'},
  {viewValue: 'SUAREZ'},
  {viewValue: 'SUCRE'},
  {viewValue: 'TIMBIO'},
  {viewValue: 'TIMBIQUI'},
  {viewValue: 'TORIBIO'},
  {viewValue: 'TOTORO'},
  {viewValue: 'VILLA RICA'}
]

